In [5]:
import numpy as np
a = np.arange(1,51).reshape(10,5)
b = np.arange(51,101).reshape(10,5)
a
b

array([[ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [4]:
a[1]

array([ 6,  7,  8,  9, 10])

In [6]:
a+b

array([[ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130],
       [132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150]])

In [7]:
np.add(a,b)

array([[ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130],
       [132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150]])

In [8]:
a-b

array([[-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50]])

In [9]:
np.subtract(a,b)

array([[-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50],
       [-50, -50, -50, -50, -50]])

In [10]:
a*b

array([[  51,  104,  159,  216,  275],
       [ 336,  399,  464,  531,  600],
       [ 671,  744,  819,  896,  975],
       [1056, 1139, 1224, 1311, 1400],
       [1491, 1584, 1679, 1776, 1875],
       [1976, 2079, 2184, 2291, 2400],
       [2511, 2624, 2739, 2856, 2975],
       [3096, 3219, 3344, 3471, 3600],
       [3731, 3864, 3999, 4136, 4275],
       [4416, 4559, 4704, 4851, 5000]])

In [12]:
np.multiply(a,b)

array([[  51,  104,  159,  216,  275],
       [ 336,  399,  464,  531,  600],
       [ 671,  744,  819,  896,  975],
       [1056, 1139, 1224, 1311, 1400],
       [1491, 1584, 1679, 1776, 1875],
       [1976, 2079, 2184, 2291, 2400],
       [2511, 2624, 2739, 2856, 2975],
       [3096, 3219, 3344, 3471, 3600],
       [3731, 3864, 3999, 4136, 4275],
       [4416, 4559, 4704, 4851, 5000]])

In [13]:
a/b

array([[0.01960784, 0.03846154, 0.05660377, 0.07407407, 0.09090909],
       [0.10714286, 0.12280702, 0.13793103, 0.15254237, 0.16666667],
       [0.18032787, 0.19354839, 0.20634921, 0.21875   , 0.23076923],
       [0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429],
       [0.29577465, 0.30555556, 0.31506849, 0.32432432, 0.33333333],
       [0.34210526, 0.35064935, 0.35897436, 0.36708861, 0.375     ],
       [0.38271605, 0.3902439 , 0.39759036, 0.4047619 , 0.41176471],
       [0.41860465, 0.42528736, 0.43181818, 0.43820225, 0.44444444],
       [0.45054945, 0.45652174, 0.46236559, 0.46808511, 0.47368421],
       [0.47916667, 0.48453608, 0.48979592, 0.49494949, 0.5       ]])

In [14]:
np.divide(a,b)

array([[0.01960784, 0.03846154, 0.05660377, 0.07407407, 0.09090909],
       [0.10714286, 0.12280702, 0.13793103, 0.15254237, 0.16666667],
       [0.18032787, 0.19354839, 0.20634921, 0.21875   , 0.23076923],
       [0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429],
       [0.29577465, 0.30555556, 0.31506849, 0.32432432, 0.33333333],
       [0.34210526, 0.35064935, 0.35897436, 0.36708861, 0.375     ],
       [0.38271605, 0.3902439 , 0.39759036, 0.4047619 , 0.41176471],
       [0.41860465, 0.42528736, 0.43181818, 0.43820225, 0.44444444],
       [0.45054945, 0.45652174, 0.46236559, 0.46808511, 0.47368421],
       [0.47916667, 0.48453608, 0.48979592, 0.49494949, 0.5       ]])

In [27]:
a = a.reshape(5,10)
b = b.reshape(10,5)
print(b)
print(a)

[[ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [28]:
print(a.shape)
print(b.shape)

(5, 10)
(10, 5)


In [29]:
a@b

array([[ 4455,  4510,  4565,  4620,  4675],
       [11805, 11960, 12115, 12270, 12425],
       [19155, 19410, 19665, 19920, 20175],
       [26505, 26860, 27215, 27570, 27925],
       [33855, 34310, 34765, 35220, 35675]])

In [30]:
a.dot(b)

array([[ 4455,  4510,  4565,  4620,  4675],
       [11805, 11960, 12115, 12270, 12425],
       [19155, 19410, 19665, 19920, 20175],
       [26505, 26860, 27215, 27570, 27925],
       [33855, 34310, 34765, 35220, 35675]])

In [31]:
b.max()

100

In [32]:
b.min()

51

In [34]:
b.argmax()    # index of the max value

49

In [35]:
np.sum(b)

3775

In [36]:
np.sum(b, axis= 1)  # rows

array([265, 290, 315, 340, 365, 390, 415, 440, 465, 490])

In [37]:
np.sum(b, axis=0)

array([735, 745, 755, 765, 775])

In [38]:
np.mean(b)

75.5

In [39]:
np.sqrt(b)

array([[ 7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849],
       [ 7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669],
       [ 7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775],
       [ 8.1240384 ,  8.18535277,  8.24621125,  8.30662386,  8.36660027],
       [ 8.42614977,  8.48528137,  8.54400375,  8.60232527,  8.66025404],
       [ 8.71779789,  8.77496439,  8.83176087,  8.88819442,  8.94427191],
       [ 9.        ,  9.05538514,  9.11043358,  9.16515139,  9.21954446],
       [ 9.2736185 ,  9.32737905,  9.38083152,  9.43398113,  9.48683298],
       [ 9.53939201,  9.59166305,  9.64365076,  9.69535971,  9.74679434],
       [ 9.79795897,  9.8488578 ,  9.89949494,  9.94987437, 10.        ]])

In [40]:
np.std(b)

14.430869689661812

In [41]:
np.log(b)

array([[3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319],
       [4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727],
       [4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748811],
       [4.33073334, 4.34380542, 4.35670883, 4.36944785, 4.38202663],
       [4.39444915, 4.40671925, 4.41884061, 4.4308168 , 4.44265126],
       [4.4543473 , 4.46590812, 4.47733681, 4.48863637, 4.49980967],
       [4.51085951, 4.52178858, 4.53259949, 4.54329478, 4.55387689],
       [4.56434819, 4.57471098, 4.58496748, 4.59511985, 4.60517019]])