In [1]:
import numpy as np

In [11]:
d1 = np.array([1,2,3,4,5])
print(d1)
print(d1.dtype) # type of data present in an array
print(type(d1)) # type of data

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [14]:
d2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(d2)
print(d2.dtype)
print(d2.size) # number of elements

[[1 2 3 4 5]
 [5 6 7 8 9]]
int32
10


In [13]:
# shape = (rows,columns)
print(d1.shape)
print(d2.shape)

(5,)
(2, 5)


In [16]:
d3 = np.array([[1,2,3,4.2,5],[5,6,7,8,9],[11,12,13,14,15]])
print(d3)
print(d3.dtype)

[[ 1.   2.   3.   4.2  5. ]
 [ 5.   6.   7.   8.   9. ]
 [11.  12.  13.  14.  15. ]]
float64


In [18]:
d3.transpose() # CONVERT ROWS INTO COLUMNS AND VICE-VERSA

array([[ 1. ,  5. , 11. ],
       [ 2. ,  6. , 12. ],
       [ 3. ,  7. , 13. ],
       [ 4.2,  8. , 14. ],
       [ 5. ,  9. , 15. ]])

In [19]:
# np.empty((rows,columns),dtype)
np.empty((4,4),dtype = int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 5439580, 4456533],
       [4522053, 6029392, 7340097, 4456560],
       [7602273, 6029409, 7274572, 6357091]])

In [20]:
np.empty((4,4),dtype = float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521816e-307],
       [6.23047842e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

In [25]:
x1 = np.ones(6) 
x2 = np.ones((3,5)) # WILL PRINT DEFAULT FLOAT VALUES
x3 = np.ones((4,4), dtype = int)
print(x1)
print(x2)
print(x3)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
y1 = np.zeros(6) 
y2 = np.zeros((3,5)) # WILL PRINT DEFAULT FLOAT VALUES
y3 = np.zeros((4,4), dtype = int)
print(y1)
print(y2)
print(y3)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
z1 = np.zeros((4,4), dtype = str) # IT WILL GIVE EMPTY OUTPUT
z2 = np.ones((4,4), dtype = str)
print(z1)
print(z2)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [30]:
P1 = np.zeros((4,4), dtype = bool) # IT WILL GIVE FALSE as an OUTPUT
P2 = np.ones((4,4), dtype = bool)
print(P1)
print(P2)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
