<a href="https://colab.research.google.com/github/koppula-Sudeep/JupyterNotebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
d1 = np.array([1,2,3,4,5])
print(d1)
print(d1.dtype) # type of data present in an array
print(type(d1)) # type of data

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [ ]:
d2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(d2)
print(d2.dtype)
print(d2.size) # number of elements

[[1 2 3 4 5]
 [5 6 7 8 9]]
int32
10


In [ ]:
# shape = (rows,columns)
print(d1.shape)
print(d2.shape)

(5,)
(2, 5)


In [ ]:
d3 = np.array([[1,2,3,4.2,5],[5,6,7,8,9],[11,12,13,14,15]])
print(d3)
print(d3.dtype)

[[ 1.   2.   3.   4.2  5. ]
 [ 5.   6.   7.   8.   9. ]
 [11.  12.  13.  14.  15. ]]
float64


In [ ]:
d3.transpose() # CONVERT ROWS INTO COLUMNS AND VICE-VERSA

array([[ 1. ,  5. , 11. ],
       [ 2. ,  6. , 12. ],
       [ 3. ,  7. , 13. ],
       [ 4.2,  8. , 14. ],
       [ 5. ,  9. , 15. ]])

In [ ]:
# np.empty((rows,columns),dtype)
np.empty((4,4),dtype = int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 5439580, 4456533],
       [4522053, 6029392, 7340097, 4456560],
       [7602273, 6029409, 7274572, 6357091]])

In [ ]:
np.empty((4,4),dtype = float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521816e-307],
       [6.23047842e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

In [ ]:
x1 = np.ones(6)
x2 = np.ones((3,5)) # WILL PRINT DEFAULT FLOAT VALUES
x3 = np.ones((4,4), dtype = int)
print(x1)
print(x2)
print(x3)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
y1 = np.zeros(6)
y2 = np.zeros((3,5)) # WILL PRINT DEFAULT FLOAT VALUES
y3 = np.zeros((4,4), dtype = int)
print(y1)
print(y2)
print(y3)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
z1 = np.zeros((4,4), dtype = str) # IT WILL GIVE EMPTY OUTPUT
z2 = np.ones((4,4), dtype = str)
print(z1)
print(z2)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [ ]:
P1 = np.zeros((4,4), dtype = bool) # IT WILL GIVE FALSE as an OUTPUT
P2 = np.ones((4,4), dtype = bool)
print(P1)
print(P2)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# np.arange(start,end,shape)
import numpy as np

a1 = np.arange(1,20)
a2 = np.arange(1,20,2)
a3 = np.arange(2,20,2)
a4 = np.arange(2,20,3)
print(a1)
print(a2)
print(a3)
print(a4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 2  4  6  8 10 12 14 16 18]
[ 2  5  8 11 14 17]


In [ ]:
a3.reshape((3,3))

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
b1 = np.arange(1,100,2)
b1.reshape((10,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

a.ravel:

1. Return only reference/view of original array
2. if you modify the array you would notice that the value of original array also changes
3. ravel is faster than flatten
4. also it does not occupies memory
5. ravel is a library level function

a.flatten:

1. return copy of original value
2. if you modify any value of this array value of original array is not affected
3. it is slower than ravel as it occupies memory
4. flatten is a method of an array object

In [ ]:
z = b1.flatten()
print(z)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
b1.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
b1.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
y = b1.ravel()   # flatten and ravel inverse the changes in reshape
print(y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
import numpy as np
b1 = np.arange(1,51)
a = b1.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
a[3,4]

20

In [ ]:
a[2:7]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
a[0:100]

In [ ]:
a[2:,1] #[rows,column]

In [ ]:
a[2:,2:5].dtype

In [ ]:
a[:,:] #[all rows,all columns]