In [2]:
# np.arange(start,end,shape)
import numpy as np

In [4]:
a1 = np.arange(1,20)
a2 = np.arange(1,20,2)
a3 = np.arange(2,20,2)
a4 = np.arange(2,20,3)
print(a1)
print(a2)
print(a3)
print(a4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 2  4  6  8 10 12 14 16 18]
[ 2  5  8 11 14 17]


In [8]:
a3.reshape((3,3))

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
b1 = np.arange(1,100,2)
b1.reshape((10,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [11]:
z = b1.flatten()
print(z)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [12]:
b1.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
b1.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
y = b1.ravel()   # flatten and ravel inverse the changes in reshape
print(y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


a.ravel:
1. return only reference/view of original array
2. if you modify the array you would notice that the value of original array also changes
3. ravel is faster than flatten
4. also it does not occupies memory
5. ravel is a library level function

a.flatten:
1. return copy of original value
2. if you modify any value of this array value of original array is not affected
3. it is slower than ravel as it occupies memory
4. flatten is a method of an array object


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed